language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
notifications:
  email:
    recipients:
      - pru.mike@gmail.com
    on_success: always
    on_failure: always
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

